[package]
name = "valkyrie-parser"
version = "0.2.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "Lexer and token definitions for Valkyrie language"
repository = "https://github.com/nyar-vm/valkyrie.rs"
license = "MPL-2.0"

[dependencies]
peginator = "0.6.0"
unicode-ident = "1.0.6"

[dependencies.valkyrie-errors]
#version = "0.0.1"
path = "../valkyrie-errors"
features = ["peginator"]

[dependencies.valkyrie-ast]
version = "0.0.0"
path = "../valkyrie-ast"

[dev-dependencies]


[build-dependencies]
