[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/valkyrie-ast",
    "projects/valkyrie-antlr",
    "projects/valkyrie-types",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"