[package]
name = "valkyrie-types"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
num = "0.4.0"
indexmap = "1.9.2"
inwelling = "0.5.0"
itertools = "0.10.5"


[dev-dependencies]

[features]
default = []
